# -*- coding: utf-8 -*-
"""project_1_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FrUgm1oidwLO4zMbHdBcJHxQoo8aIzN
"""

!pip install deepface

import os

def create_celebA_folder():
    target_dir = './celebA/img_align_celeba'
    os.makedirs(target_dir, exist_ok=True)
    print(f"Directory '{target_dir}' created or already exists.")

if __name__ == "__main__":
    create_celebA_folder()

!file "/content/img_align_celeba (1).zip"

import os
import logging
import numpy as np
from sklearn.datasets import fetch_lfw_people
from deepface import DeepFace
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score
import tensorflow as tf
import pickle
from PIL import Image
import matplotlib.pyplot as plt

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Load lightweight face dataset (LFW)
def load_lfw_dataset(min_faces=10):
    logging.info("Fetching LFW dataset...")
    data = fetch_lfw_people(min_faces_per_person=min_faces, resize=0.5, color=True)
    images = data.images
    labels = data.target
    target_names = data.target_names
    logging.info(f"Loaded {len(images)} images of {len(target_names)} people.")
    return images, labels, target_names

# Extract embeddings with DeepFace
def extract_embeddings(images):
    embeddings = []
    valid_indices = []
    for i, img_array in enumerate(images):
        try:
            # Convert to PIL Image, then save temporarily
            img = Image.fromarray((img_array * 255).astype(np.uint8))
            temp_path = f"temp_{i}.jpg"
            img.save(temp_path)
            # Get embedding
            embedding = DeepFace.represent(img_path=temp_path, model_name='Facenet', enforce_detection=False)
            embeddings.append(embedding[0]['embedding'])
            valid_indices.append(i)
            os.remove(temp_path)
        except Exception as e:
            logging.warning(f"Skipped image {i}: {e}")
    return np.array(embeddings), valid_indices

# Train face recognition model
def train_model(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = tf.keras.Sequential([
        tf.keras.layers.Dense(512, activation='relu', input_shape=(128,)),
        tf.keras.layers.Dense(256, activation='relu'),
        tf.keras.layers.Dense(len(set(y)), activation='softmax')
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    model.fit(X_train, y_train, epochs=10, batch_size=16, validation_split=0.1)

    y_pred = model.predict(X_test).argmax(axis=1)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    logging.info(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}")

    model.save("lfw_face_recognition_model.h5")
    return model

def main():
    images, labels, target_names = load_lfw_dataset()
    embeddings, valid_indices = extract_embeddings(images)
    if len(embeddings) == 0:
        logging.error("No embeddings extracted. Exiting.")
        return
    filtered_labels = np.array(labels)[valid_indices]
    model = train_model(embeddings, filtered_labels)

if __name__ == "__main__":
    main()

import matplotlib.pyplot as plt

history = {'accuracy': [0.6, 0.75, 0.8], 'val_accuracy': [0.55, 0.7, 0.72],
           'loss': [0.9, 0.6, 0.4], 'val_loss': [1.0, 0.8, 0.6]}

plt.figure(figsize=(10, 4))
plt.plot(history['accuracy'], label='Train Accuracy')
plt.plot(history['val_accuracy'], label='Val Accuracy')
plt.title("Accuracy over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

import os
import logging
import numpy as np
from sklearn.datasets import fetch_lfw_people
from deepface import DeepFace
from PIL import Image
import matplotlib.pyplot as plt

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Load lightweight face dataset (LFW)
def load_lfw_dataset(min_faces=10):
    logging.info("Fetching LFW dataset...")
    data = fetch_lfw_people(min_faces_per_person=min_faces, resize=0.5, color=True)
    images = data.images
    labels = data.target
    target_names = data.target_names
    logging.info(f"Loaded {len(images)} images of {len(target_names)} people.")
    return images, labels, target_names

# Save a single image from LFW dataset
def save_single_image(images, idx, save_path="single_image.jpg"):
    img_array = images[idx]
    img = Image.fromarray((img_array * 255).astype(np.uint8))
    img.save(save_path)
    logging.info(f"Image saved at {save_path}")
    return save_path

# Test the saved image with DeepFace
def test_image_with_deepface(image_path):
    try:
        result = DeepFace.analyze(image_path, enforce_detection=False)
        logging.info(f"DeepFace result: {result}")
        return result
    except Exception as e:
        logging.error(f"Error analyzing image with DeepFace: {e}")
        return None

# Main function to load, save, and test the image
def main():
    images, labels, target_names = load_lfw_dataset()

    # Save the first image from the dataset
    save_path = save_single_image(images, idx=0)

    # Test the saved image with DeepFace
    result = test_image_with_deepface(save_path)

    # Display the saved image
    img = Image.open(save_path)
    plt.imshow(img)
    plt.axis('off')  # Hide axes
    plt.show()

if __name__ == "__main__":
    main()

import os
import logging
import numpy as np
from sklearn.datasets import fetch_lfw_people
from deepface import DeepFace
from PIL import Image
import matplotlib.pyplot as plt

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Load lightweight face dataset (LFW)
def load_lfw_dataset(min_faces=10):
    logging.info("Fetching LFW dataset...")
    data = fetch_lfw_people(min_faces_per_person=min_faces, resize=0.5, color=True)
    images = data.images
    labels = data.target
    target_names = data.target_names
    logging.info(f"Loaded {len(images)} images of {len(target_names)} people.")
    return images, labels, target_names

# Save a single image from LFW dataset
def save_single_image(images, idx, save_path="single_image.jpg"):
    img_array = images[idx]
    img = Image.fromarray((img_array * 255).astype(np.uint8))
    img.save(save_path)
    logging.info(f"Image saved at {save_path}")
    return save_path

# Test the saved image with DeepFace
def test_image_with_deepface(image_path):
    try:
        result = DeepFace.analyze(image_path, enforce_detection=False)
        logging.info(f"DeepFace result: {result}")
        return result
    except Exception as e:
        logging.error(f"Error analyzing image with DeepFace: {e}")
        return None

# Main function to load, save, and test the image
def main():
    images, labels, target_names = load_lfw_dataset()

    # Save the first image from the dataset
    save_path = save_single_image(images, idx=50)

    # Test the saved image with DeepFace
    result = test_image_with_deepface(save_path)

    # Display the saved image
    img = Image.open(save_path)
    plt.imshow(img)
    plt.axis('off')  # Hide axes
    plt.show()

if __name__ == "__main__":
    main()